// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjNu33OargjPOUYdsSaRIGrP1bnnacTEY',
    appId: '1:295643914349:web:865383a85e1c045fb9df64',
    messagingSenderId: '295643914349',
    projectId: 'medlink-40',
    authDomain: 'medlink-40.firebaseapp.com',
    storageBucket: 'medlink-40.firebasestorage.app',
    measurementId: 'G-FHW81ZVL7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYDQpUVKccCeej7ujdWjNluAKD77InL0',
    appId: '1:295643914349:android:e70042f8fa4e929cb9df64',
    messagingSenderId: '295643914349',
    projectId: 'medlink-40',
    storageBucket: 'medlink-40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCodqaE53p056tUyjsrU4qQl_BKnWHhwo',
    appId: '1:295643914349:ios:d762d41e5a12f773b9df64',
    messagingSenderId: '295643914349',
    projectId: 'medlink-40',
    storageBucket: 'medlink-40.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCodqaE53p056tUyjsrU4qQl_BKnWHhwo',
    appId: '1:295643914349:ios:d762d41e5a12f773b9df64',
    messagingSenderId: '295643914349',
    projectId: 'medlink-40',
    storageBucket: 'medlink-40.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjNu33OargjPOUYdsSaRIGrP1bnnacTEY',
    appId: '1:295643914349:web:17f95938c6e2b180b9df64',
    messagingSenderId: '295643914349',
    projectId: 'medlink-40',
    authDomain: 'medlink-40.firebaseapp.com',
    storageBucket: 'medlink-40.firebasestorage.app',
    measurementId: 'G-WSK66F0JWZ',
  );
}
